version: "3.9"
services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HTTP_PORT}:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mysql
    networks:
      - app-network
    command: npm run start

  mysql:
    container_name: mysql
    image: mysql:8
    ports:
      - "${MYSQL_PORT}:3306"
    env_file: ./docker/mysql/.env
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  pma:
    container_name: pma
    image: phpmyadmin:5.1
    ports:
      - "${PMA_PORT}:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_PORT=${MYSQL_PORT}
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    # command: npm run start:dev

